### ISSUE TITLE
Slashlifetime and other lifetimes switching to bigger percentages when being applied

### ISSUE THREAD

**Issue by PiXel214** [Shadnix-was-taken/BeatSaber-ParticleOverdrive#3] opened 2020-06-26 17:24 UTC
So, quick issue and since there are no other issues about this.

Whenever you set the slashlifetime to lets say 20% and apply it and press okay, it defaults it to 200%.
This is also the same for the bomb settings, and somethimes it doesn't even have an effect for lets say setting everything to 0%. then there are still particles like slash and bomb particles. 

this is kinda annoying since i can't play without, but i also can't play with 200% particles O_O.
(it's also weird because some have this issue and some don't) (i have tried this: reinstalling the whole game including mods, I tried to delete the mod itself including its .ini file. still no luck :/

**Comment by Shadnix-was-taken** [comment] 2020-09-06 19:33
Oh - sorry for the late reply - apparently I hadn't enabled notifications for this repository yet. Just fixed it.

I'm not able to reproduce the described problem, so I'm not quite sure how to handle it right now. Does the problem actually still exist on the current Beat Saber version with up-to-date mods?

And since there were problems with number formats in the past with different mods: What is the language of your Windows operating system?

**Comment by PiXel214** [comment] 2020-09-06 19:43
Hey! That's okay XD. 
So this was an issue with the the 1.10.0 update, But since 1.11.0(1) came out everything works fine! I don't know how it happend but it seems to be fixed now! ^^

**Comment by PiXel214** [comment] 2020-09-06 19:44
Oh sorry forgot to type this! My windows 10 language is set to Dutch.

**Comment by Shadnix-was-taken** [comment] 2020-09-06 20:10
Alright. As discussed, I'm gonna close this issue then. Again, sorry for the late reply.

**Closed as completed by Shadnix-was-taken** 2020-09-06 20:10 UTC
